name = "random-picture-api"
main = "src/index.js"
compatibility_date = "2023-01-01"

[vars]
IMAGES = """
https://raw.githubusercontent.com/1143520/picture-api/main/public/01.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/02.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/03.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/04.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/05.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/06.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/07.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/08.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/09.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/10.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/11.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/12.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/13.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/14.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/15.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/16.jpg
https://raw.githubusercontent.com/1143520/picture-api/main/public/17.png
https://raw.githubusercontent.com/1143520/picture-api/main/public/18.png
https://raw.githubusercontent.com/1143520/picture-api/main/public/19.png
https://raw.githubusercontent.com/1143520/picture-api/main/public/20.png
https://raw.githubusercontent.com/1143520/picture-api/main/public/21.png
https://raw.githubusercontent.com/1143520/picture-api/main/public/22.png
https://raw.githubusercontent.com/1143520/picture-api/main/public/23.png
https://raw.githubusercontent.com/1143520/picture-api/main/public/24.png
https://raw.githubusercontent.com/1143520/picture-api/main/public/25.png
https://raw.githubusercontent.com/1143520/picture-api/main/public/26.png
https://raw.githubusercontent.com/1143520/picture-api/main/public/27.png
https://raw.githubusercontent.com/1143520/picture-api/main/public/28.png
https://raw.githubusercontent.com/1143520/picture-api/main/public/29.png
https://raw.githubusercontent.com/1143520/picture-api/main/public/30.jpeg
"""